name: tests
on: [push, pull_request]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Set up Go 1.17
              uses: actions/setup-go@v1
              with:
                  go-version: 1.17
            - name: Check out code into the Go module directory
              uses: actions/checkout@v1
              with:
                  fetch-depth: 1
                  path: go/src/github.com/rafaelrubbioli/expenses
            - name: GolangCI-Lint
              run: |
                  curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s v1.19.1
                  ./bin/golangci-lint run
              env:
                  GOPATH: /home/runner/work/expenses/go
            - name: Test
              run: |
                  go test -race -cover ./...
              env:
                  GOPATH: /home/runner/work/expenses/go

